name: Build Docker Image

on:
  push: {}

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY_INTERFACES }}
            ${{ secrets.SSH_KEY_STABLE_DIFFUSION }}
      - run: |
          git submodule update --init --recursive
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max 
          outputs: |
            type=local,dest=${{ runner.temp }}/docker-build      
      - uses: actions/upload-artifact@v3
        with:
         name: gooseai
         path: ${{ runner.temp }}/docker-build/gooseai
